-- Synagogue members admin
-- Run this once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.synagogue_members (
  id uuid primary key default gen_random_uuid(),
  member_number bigint generated by default as identity,
  synagogue_id uuid not null references public.synagogues(id) on delete cascade,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  full_name text not null,
  login_email text not null,
  phone text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  postal_code text,
  notes text,
  status text not null default 'pending'
    check (status in ('pending','approved','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (synagogue_id, login_email)
);

create index if not exists synagogue_members_synagogue_id_idx
  on public.synagogue_members(synagogue_id);

create index if not exists synagogue_members_status_idx
  on public.synagogue_members(synagogue_id,status);

alter table public.synagogue_members enable row level security;

-- The browser page uses the secured Edge Function for all member operations.
-- No anon/authenticated direct table policy is required.
-- service_role used inside the Edge Function bypasses RLS.

create or replace function public.touch_synagogue_member_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_synagogue_members_updated_at on public.synagogue_members;
create trigger trg_synagogue_members_updated_at
before update on public.synagogue_members
for each row execute function public.touch_synagogue_member_updated_at();

-- Optional helper view for the master dashboard.
create or replace view public.synagogue_member_counts as
select
  synagogue_id,
  count(*)::bigint as total_members,
  count(*) filter (where status='pending')::bigint as pending_members,
  count(*) filter (where status='approved')::bigint as approved_members,
  count(*) filter (where status='suspended')::bigint as suspended_members
from public.synagogue_members
group by synagogue_id;
